:: 
:: Get the CYGWIN dependencies for our runtime folder.
:: 

:: Make temp folder if it does not exist
if not exist "temp" (
    mkdir temp
)
cd temp
powershell -Command "& Invoke-WebRequest -OutFile .\setup.exe https://cygwin.com/setup-x86_64.exe"
.\setup.exe -q -n -N -d -B -R .\ -s https://mirrors.sonic.net/cygwin -l %cd% -P wget
set PATH=%cd%\bin;%PATH%;
wget https://rawgit.com/transcode-open/apt-cyg/master/apt-cyg -P ./
install ./apt-cyg /bin

:: Install OpenSSH
bash apt-cyg install openssh

:: copy dependencies to runtime folder for Windows
mkdir -p "..\runtime\win32_x86"
copy /Y bin\tar.exe "..\runtime\win32_x86\tar.exe"
copy /Y bin\xz.exe "..\runtime\win32_x86\xz.exe"
copy /Y bin\ssh.exe "..\runtime\win32_x86\ssh.exe"
copy /Y bin\cygwin1.dll "..\runtime\win32_x86\cygwin1.dll"
copy /Y bin\cygiconv-2.dll "..\runtime\win32_x86\cygiconv-2.dll"
copy /Y bin\cygintl-8.dll "..\runtime\win32_x86\cygintl-8.dll"
copy /Y bin\cyglzma-5.dll "..\runtime\win32_x86\cyglzma-5.dll"
copy /Y bin\cygcrypto-1.1.dll "..\runtime\win32_x86\cygcrypto-1.1.dll"
copy /Y bin\cygz.dll "..\runtime\win32_x86\cygz.dll"
copy /Y bin\cyggssapi_krb5-2.dll "..\runtime\win32_x86\cyggssapi_krb5-2.dll"
copy /Y bin\cygk5crypto-3.dll "..\runtime\win32_x86\cygk5crypto-3.dll"
copy /Y bin\cygkrb5-3.dll "..\runtime\win32_x86\cygkrb5-3.dll"
copy /Y bin\cygkrb5support-0.dll "..\runtime\win32_x86\cygkrb5support-0.dll"
copy /Y bin\cygcom_err-2.dll "..\runtime\win32_x86\cygcom_err-2.dll"
copy /Y bin\cyggcc_s-seh-1.dll "..\runtime\win32_x86\cyggcc_s-seh-1.dll"

:: Cleanup
cd ..
rmdir /s /q temp

:: assume default qemu is installed (i.e. via devstia-vm/build-vm-win-amd64.bat)
copy /Y "C:\Program Files\qemu\qemu-system-x86_64.exe" ".\runtime\win32_x86\qemu-system-x86_64.exe"
copy /Y "C:\Program Files\qemu\sdl2.dll" ".\runtime\win32_x86\sdl2.dll"
copy /Y "C:\Program Files\qemu\sdl2_image.dll" ".\runtime\win32_x86\sdl2_image.dll"
copy /Y "C:\Program Files\qemu\libjpeg-8.dll" ".\runtime\win32_x86\libjpeg-8.dll"
copy /Y "C:\Program Files\qemu\libjxl.dll" ".\runtime\win32_x86\libjxl.dll"
copy /Y "C:\Program Files\qemu\libgcc_s_seh-1.dll" ".\runtime\win32_x86\libgcc_s_seh-1.dll"
copy /Y "C:\Program Files\qemu\libstdc++-6.dll" ".\runtime\win32_x86\libstdc++-6.dll"
copy /Y "C:\Program Files\qemu\libwinpthread-1.dll" ".\runtime\win32_x86\libwinpthread-1.dll"
copy /Y "C:\Program Files\qemu\libbrotlidec.dll" ".\runtime\win32_x86\libbrotlidec.dll"
copy /Y "C:\Program Files\qemu\libbrotlicommon.dll" ".\runtime\win32_x86\libbrotlicommon.dll"
copy /Y "C:\Program Files\qemu\libbrotlienc.dll" ".\runtime\win32_x86\libbrotlienc.dll"
copy /Y "C:\Program Files\qemu\liblzma-5.dll" ".\runtime\win32_x86\liblzma-5.dll"
copy /Y "C:\Program Files\qemu\libhwy.dll" ".\runtime\win32_x86\libhwy.dll"
copy /Y "C:\Program Files\qemu\liblcms2-2.dll" ".\runtime\win32_x86\liblcms2-2.dll"
copy /Y "C:\Program Files\qemu\libpng16-16.dll" ".\runtime\win32_x86\libpng16-16.dll"
copy /Y "C:\Program Files\qemu\libtiff-6.dll" ".\runtime\win32_x86\libtiff-6.dll"
copy /Y "C:\Program Files\qemu\libdeflate.dll" ".\runtime\win32_x86\libdeflate.dll"
copy /Y "C:\Program Files\qemu\libjbig-0.dll" ".\runtime\win32_x86\libjbig-0.dll"
copy /Y "C:\Program Files\qemu\liblerc.dll" ".\runtime\win32_x86\liblerc.dll"
copy /Y "C:\Program Files\qemu\libwebp-7.dll" ".\runtime\win32_x86\libwebp-7.dll"
copy /Y "C:\Program Files\qemu\zlib1.dll" ".\runtime\win32_x86\zlib1.dll"
copy /Y "C:\Program Files\qemu\libzstd.dll" ".\runtime\win32_x86\libzstd.dll"
copy /Y "C:\Program Files\qemu\libsharpyuv-0.dll" ".\runtime\win32_x86\libsharpyuv-0.dll"
copy /Y "C:\Program Files\qemu\brlapi-0.8.dll" ".\runtime\win32_x86\brlapi-0.8.dll"
copy /Y "C:\Program Files\qemu\libbz2-1.dll" ".\runtime\win32_x86\libbz2-1.dll"
copy /Y "C:\Program Files\qemu\libcacard-0.dll" ".\runtime\win32_x86\libcacard-0.dll"
copy /Y "C:\Program Files\qemu\libglib-2.0-0.dll" ".\runtime\win32_x86\libglib-2.0-0.dll"
copy /Y "C:\Program Files\qemu\libintl-8.dll" ".\runtime\win32_x86\libintl-8.dll"
copy /Y "C:\Program Files\qemu\libnspr4.dll" ".\runtime\win32_x86\libnspr4.dll"
copy /Y "C:\Program Files\qemu\nss3.dll" ".\runtime\win32_x86\nss3.dll"
copy /Y "C:\Program Files\qemu\nssutil3.dll" ".\runtime\win32_x86\nssutil3.dll"
copy /Y "C:\Program Files\qemu\libplc4.dll" ".\runtime\win32_x86\libplc4.dll"
copy /Y "C:\Program Files\qemu\libplds4.dll" ".\runtime\win32_x86\libplds4.dll"
copy /Y "C:\Program Files\qemu\libcairo-2.dll" ".\runtime\win32_x86\libcairo-2.dll"
copy /Y "C:\Program Files\qemu\libfontconfig-1.dll" ".\runtime\win32_x86\libfontconfig-1.dll"
copy /Y "C:\Program Files\qemu\libexpat-1.dll" ".\runtime\win32_x86\libexpat-1.dll"
copy /Y "C:\Program Files\qemu\libfreetype-6.dll" ".\runtime\win32_x86\libfreetype-6.dll"
copy /Y "C:\Program Files\qemu\libiconv-2.dll" ".\runtime\win32_x86\libiconv-2.dll"
copy /Y "C:\Program Files\qemu\libharfbuzz-0.dll" ".\runtime\win32_x86\libharfbuzz-0.dll"
copy /Y "C:\Program Files\qemu\libgraphite2.dll" ".\runtime\win32_x86\libgraphite2.dll"
copy /Y "C:\Program Files\qemu\libpixman-1-0.dll" ".\runtime\win32_x86\libpixman-1-0.dll"
copy /Y "C:\Program Files\qemu\libcapstone.dll" ".\runtime\win32_x86\libcapstone.dll"
copy /Y "C:\Program Files\qemu\libcurl-4.dll" ".\runtime\win32_x86\libcurl-4.dll"
copy /Y "C:\Program Files\qemu\libidn2-0.dll" ".\runtime\win32_x86\libidn2-0.dll"
copy /Y "C:\Program Files\qemu\libunistring-5.dll" ".\runtime\win32_x86\libunistring-5.dll"
copy /Y "C:\Program Files\qemu\libpsl-5.dll" ".\runtime\win32_x86\libpsl-5.dll"
copy /Y "C:\Program Files\qemu\libssh2-1.dll" ".\runtime\win32_x86\libssh2-1.dll"
copy /Y "C:\Program Files\qemu\libepoxy-0.dll" ".\runtime\win32_x86\libepoxy-0.dll"
copy /Y "C:\Program Files\qemu\libfdt-1.dll" ".\runtime\win32_x86\libfdt-1.dll"
copy /Y "C:\Program Files\qemu\libgdk-3-0.dll" ".\runtime\win32_x86\libgdk-3-0.dll"
copy /Y "C:\Program Files\qemu\libcairo-gobject-2.dll" ".\runtime\win32_x86\libcairo-gobject-2.dll"
copy /Y "C:\Program Files\qemu\libgobject-2.0-0.dll" ".\runtime\win32_x86\libgobject-2.0-0.dll"
copy /Y "C:\Program Files\qemu\libfribidi-0.dll" ".\runtime\win32_x86\libfribidi-0.dll"
copy /Y "C:\Program Files\qemu\libgdk_pixbuf-2.0-0.dll" ".\runtime\win32_x86\libgdk_pixbuf-2.0-0.dll"
copy /Y "C:\Program Files\qemu\libgio-2.0-0.dll" ".\runtime\win32_x86\libgio-2.0-0.dll"
copy /Y "C:\Program Files\qemu\libpangowin32-1.0-0.dll" ".\runtime\win32_x86\libpangowin32-1.0-0.dll"
copy /Y "C:\Program Files\qemu\libthai-0.dll" ".\runtime\win32_x86\libthai-0.dll"
copy /Y "C:\Program Files\qemu\libdatrie-1.dll" ".\runtime\win32_x86\libdatrie-1.dll"
copy /Y "C:\Program Files\qemu\libpangocairo-1.0-0.dll" ".\runtime\win32_x86\libpangocairo-1.0-0.dll"
copy /Y "C:\Program Files\qemu\libpango-1.0-0.dll" ".\runtime\win32_x86\libpango-1.0-0.dll"
copy /Y "C:\Program Files\qemu\libpangoft2-1.0-0.dll" ".\runtime\win32_x86\libpangoft2-1.0-0.dll"
copy /Y "C:\Program Files\qemu\libgnutls-30.dll" ".\runtime\win32_x86\libgnutls-30.dll"
copy /Y "C:\Program Files\qemu\libgmp-10.dll" ".\runtime\win32_x86\libgmp-10.dll"
copy /Y "C:\Program Files\qemu\libhogweed-6.dll" ".\runtime\win32_x86\libhogweed-6.dll"
copy /Y "C:\Program Files\qemu\libnettle-8.dll" ".\runtime\win32_x86\libnettle-8.dll"
copy /Y "C:\Program Files\qemu\libp11-kit-0.dll" ".\runtime\win32_x86\libp11-kit-0.dll"
copy /Y "C:\Program Files\qemu\libffi-8.dll" ".\runtime\win32_x86\libffi-8.dll"
copy /Y "C:\Program Files\qemu\libtasn1-6.dll" ".\runtime\win32_x86\libtasn1-6.dll"
copy /Y "C:\Program Files\qemu\libgtk-3-0.dll" ".\runtime\win32_x86\libgtk-3-0.dll"
copy /Y "C:\Program Files\qemu\libatk-1.0-0.dll" ".\runtime\win32_x86\libatk-1.0-0.dll"
copy /Y "C:\Program Files\qemu\libgmodule-2.0-0.dll" ".\runtime\win32_x86\libgmodule-2.0-0.dll"
copy /Y "C:\Program Files\qemu\libjack64.dll" ".\runtime\win32_x86\libjack64.dll"
copy /Y "C:\Program Files\qemu\libdb-6.0.dll" ".\runtime\win32_x86\libdb-6.0.dll"
copy /Y "C:\Program Files\qemu\libsystre-0.dll" ".\runtime\win32_x86\libsystre-0.dll"
copy /Y "C:\Program Files\qemu\libtre-5.dll" ".\runtime\win32_x86\libtre-5.dll"
copy /Y "C:\Program Files\qemu\liblzo2-2.dll" ".\runtime\win32_x86\liblzo2-2.dll"
copy /Y "C:\Program Files\qemu\libncursesw6.dll" ".\runtime\win32_x86\libncursesw6.dll"
copy /Y "C:\Program Files\qemu\libnfs-14.dll" ".\runtime\win32_x86\libnfs-14.dll"
copy /Y "C:\Program Files\qemu\libsasl2-3.dll" ".\runtime\win32_x86\libsasl2-3.dll"
copy /Y "C:\Program Files\qemu\libslirp-0.dll" ".\runtime\win32_x86\libslirp-0.dll"
copy /Y "C:\Program Files\qemu\libsnappy.dll" ".\runtime\win32_x86\libsnappy.dll"
copy /Y "C:\Program Files\qemu\libspice-server-1.dll" ".\runtime\win32_x86\libspice-server-1.dll"
copy /Y "C:\Program Files\qemu\libcrypto-3-x64.dll" ".\runtime\win32_x86\libcrypto-3-x64.dll"
copy /Y "C:\Program Files\qemu\libgstapp-1.0-0.dll" ".\runtime\win32_x86\libgstapp-1.0-0.dll"
copy /Y "C:\Program Files\qemu\libgstbase-1.0-0.dll" ".\runtime\win32_x86\libgstbase-1.0-0.dll"
copy /Y "C:\Program Files\qemu\libgstreamer-1.0-0.dll" ".\runtime\win32_x86\libgstreamer-1.0-0.dll"
copy /Y "C:\Program Files\qemu\libopus-0.dll" ".\runtime\win32_x86\libopus-0.dll"
copy /Y "C:\Program Files\qemu\liborc-0.4-0.dll" ".\runtime\win32_x86\liborc-0.4-0.dll"
copy /Y "C:\Program Files\qemu\libssl-3-x64.dll" ".\runtime\win32_x86\libssl-3-x64.dll"
copy /Y "C:\Program Files\qemu\libssh.dll" ".\runtime\win32_x86\libssh.dll"
copy /Y "C:\Program Files\qemu\libusb-1.0.dll" ".\runtime\win32_x86\libusb-1.0.dll"
copy /Y "C:\Program Files\qemu\libusbredirparser-1.dll" ".\runtime\win32_x86\libusbredirparser-1.dll"
copy /Y "C:\Program Files\qemu\libvirglrenderer-1.dll" ".\runtime\win32_x86\libvirglrenderer-1.dll"
copy /Y "C:\Program Files\qemu\libssp-0.dll" ".\runtime\win32_x86\libssp-0.dll"
copy /Y "C:\Program Files\qemu\libpcre2-8-0.dll" ".\runtime\win32_x86\libpcre2-8-0.dll"
copy /Y "C:\Program Files\qemu\liblz4.dll" ".\runtime\win32_x86\liblz4.dll"

mkdir -p ".\runtime\win32_x86\share"
copy /Y "C:\Program Files\qemu\share\kvmvapic.bin" ".\runtime\win32_x86\share\kvmvapic.bin"
copy /Y "C:\Program Files\qemu\share\vgabios-virtio.bin" ".\runtime\win32_x86\share\vgabios-virtio.bin"
copy /Y "C:\Program Files\qemu\share\efi-e1000e.rom" ".\runtime\win32_x86\share\efi-e1000e.rom"
